######################################################################
# Automatically generated by qmake (2.01a) mar feb 23 23:48:56 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ball.h MyWidget.h MyWindow.h
SOURCES += Ball.cpp main.cpp MyWidget.cpp MyWindow.cpp

# Qt modules
QT += core gui widgets